2025-02-25 17:53:47,964 INFO    MainThread:29852 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-25 17:53:47,966 INFO    MainThread:29852 [wandb_setup.py:_flush():67] Configure stats pid to 29852
2025-02-25 17:53:47,966 INFO    MainThread:29852 [wandb_setup.py:_flush():67] Loading settings from C:\Users\RAMKUMAR\.config\wandb\settings
2025-02-25 17:53:47,966 INFO    MainThread:29852 [wandb_setup.py:_flush():67] Loading settings from C:\Users\RAMKUMAR\Desktop\iitm\sem2\DL\A1\wandb\settings
2025-02-25 17:53:47,966 INFO    MainThread:29852 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-25 17:53:47,966 INFO    MainThread:29852 [wandb_init.py:setup_run_log_directory():647] Logging user logs to C:\Users\RAMKUMAR\Desktop\iitm\sem2\DL\A1\wandb\run-20250225_175347-7w0mlbll\logs\debug.log
2025-02-25 17:53:47,966 INFO    MainThread:29852 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to C:\Users\RAMKUMAR\Desktop\iitm\sem2\DL\A1\wandb\run-20250225_175347-7w0mlbll\logs\debug-internal.log
2025-02-25 17:53:47,966 INFO    MainThread:29852 [wandb_init.py:init():761] calling init triggers
2025-02-25 17:53:47,966 INFO    MainThread:29852 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.02, 'architecture': 'CNN', 'dataset': 'CIFAR-100', 'epochs': 10, '_wandb': {}}
2025-02-25 17:53:47,966 INFO    MainThread:29852 [wandb_init.py:init():784] starting backend
2025-02-25 17:53:47,966 INFO    MainThread:29852 [wandb_init.py:init():788] sending inform_init request
2025-02-25 17:53:48,033 INFO    MainThread:29852 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-02-25 17:53:48,033 INFO    MainThread:29852 [wandb_init.py:init():803] backend started and connected
2025-02-25 17:53:48,034 INFO    MainThread:29852 [wandb_init.py:init():896] updated telemetry
2025-02-25 17:53:48,035 INFO    MainThread:29852 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-02-25 17:53:50,743 ERROR   MainThread:29852 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\RAMKUMAR\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RAMKUMAR\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 968, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 404 Not Found: {"errors":[{"message":"entity my-awesome-team-name not found during upsertBucket","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2025-02-25 17:53:50,760 WARNING MsgRouterThr:29852 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "C:\Users\RAMKUMAR\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\interface\router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RAMKUMAR\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RAMKUMAR\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\RAMKUMAR\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\interface\router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RAMKUMAR\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\interface\router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-02-25 17:53:50,760 INFO    MsgRouterThr:29852 [mailbox.py:close():115] Closing mailbox, abandoning 0 handles.
